export const ROUTES = {
  HOMEPAGE_ROUTE: "/",
  PROFILEPAGE_ROUTE: "/profil",
  ANGEBOTE_ROUTE: "/angebote",
  GESUCHE_ROUTE: "/gesuche",
  BEWERTUNGEN_ROUTE: "/bewertungen",
  BEWERTUNG_ABGEBEN_ROUTE: "/bewertung-abgeben",
  FAHRTEN_DETAILANSICHT_ROUTE: "/fahrt-detailansicht",
  FAHRTEN_AUFLISTUNG_ROUTE: "/meine-fahrten",
  OTHER_PROFILEPAGE_ROUTE: "/profil/:id",
  FAHRTEN_ANLAGE_ROUTE: "/fahrten-anlage",
  FAHRZEUGVERWALTUNG_ROUTE: "/fahrzeugverwaltung",
  BEZAHLUNG_FIXPREIS_ROUTE: "/bezahlung-fixpreis",
  BEZAHLUNG_VARIABEL_ROUTE: "/bezahlung-variabel",
  CHAT_ROUTE: "/chat",
};
